### ISSUE TITLE
Envelope draft "completion" without signature

### ISSUE THREAD

**Issue by samlown** [invopop/gobl.cli#12]
If the GOBL document has a `draft: true` in the headers, we should not generate a signature. For example, take the following source:

```yaml
head:
  draft: true
doc:
  $schema: "https://gobl.org/draft-0/note/message"
  title: "Test Message"
  content: |-
    We hope you like this test message!
```

Should result in a GOBL Envelope like the following, with no `sigs` field:

```json
{
  "$schema": "https://gobl.org/draft-0/envelope",
  "head": {
    "uuid": "8e69dd09-9adb-11ec-82ed-665181255c0a",
    "draft": true,
    "dig": {
      "alg": "sha256",
      "val": "45ac3115c8569a1789e58af8d0dc91ef3baa1fb71daaf38f5aef94f82b4d0033"
    }
  },
  "doc": {
    "$schema": "https://gobl.org/draft-0/note/message",
    "title": "Test Message",
    "content": "We hope you like this test message!"
  }
}
```
